config/routes.rb
require "admin_constraint"

SamsaWebsite::Application.routes.draw do
  match "/auth/:provider/callback", to: "sessions#create", via: [:get, :post]

  get "login", to: "sessions#index", as: :login
  get "logout", to: "sessions#destroy", as: :logout
  post "game_download", to: "game_download#create"

  resources :products, only: :index
  resources :news, only: :index

  concern :commentable do
    member do
      get :random_comment
    end
    resources :comments, only: :create do
      member do
        post "vote/:value", to: "comments#vote", as: :vote
      end
    end
  end

  resources :pages, only: :show do
    concerns :commentable
  end
  resources :posts, path: :news, only: :show do
    concerns :commentable
  end

  get :admin, to: "admin#index", constraints: AdminConstraint.new
  namespace :admin do
    resources :pages, only: [:index, :show]
    resources :preferences
    resources :media
    resources :header_characters
    resources :products
    resources :game_versions
    resources :posts do
      collection do
        post :preview
      end
    end
    resources :users do
      member do
        get :admin
        get :ban
      end
    end
    resources :comments do
      member do
        post :toggle
      end
    end
  end

  root "pages#index"

  get "/:id", to: "posts#show"
end

app/models/attachment.rb
# == Schema Information
#
# Table name: attachments
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  file       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Attachment < ActiveRecord::Base
# uploaders
  mount_uploader :file, AttachmentFileUploader

# validations
  validates :name, presence: true

# callbacks
  before_validation :ensure_name

# methods
  def ensure_name
    self.name = file_name if name.blank?
  end

  def file_name
    file.to_s.split("/").last.split(".").first
  end
end

app/views/admin/attachments/_attachment.html.slim
.model_on_list
  h3 = attachment.name
  .row
    .col-xs-1
      = link_to edit_admin_medium_path(attachment), class: "btn btn-sm btn-default" do
        span.glyphicon.glyphicon-edit
    .col-xs-1
      = link_to admin_medium_path(attachment), method: :delete, class: "btn btn-sm btn-danger" do
        span.glyphicon.glyphicon-remove
    .col-xs-6
      = attachment.file_link

app/views/admin/attachments/_form.html.slim
h1 = "#{attachment.new_record? ? "Agregar" : "Editar"} multimedia"

- url = attachment.new_record? ? admin_media_path : admin_medium_path(attachment)

= simple_form_for [:admin, attachment], url: url do |f|
  = f.hidden_field :file_cache
  .form-group = f.input :file, label: "Archivo"
  - if f.object.file?
    = f.object.decorate.file_link
  .form-group = f.input :name, label: "Nombre", required: false, input_html: { class: "form-control" }
  .actions
    = link_to "Cancelar", admin_media_path, class: "btn btn-link"
    = f.submit "Enviar", class: "btn btn-primary", data: { disable_with: "Enviando" }