config/routes.rb
require "admin_constraint"

SamsaWebsite::Application.routes.draw do
  match "/auth/:provider/callback", to: "sessions#create", via: [:get, :post]

  get "login", to: "sessions#index", as: :login
  get "logout", to: "sessions#destroy", as: :logout
  post "game_download", to: "game_download#create"

  resources :products, only: :index
  resources :news, only: :index

  concern :commentable do
    member do
      get :random_comment
    end
    resources :comments, only: :create do
      member do
        post "vote/:value", to: "comments#vote", as: :vote
      end
    end
  end

  resources :pages, only: :show do
    concerns :commentable
  end
  resources :posts, path: :news, only: :show do
    concerns :commentable
  end

  get :admin, to: "admin#index", constraints: AdminConstraint.new
  namespace :admin do
    resources :pages, only: [:index, :show]
    resources :preferences
    resources :media
    resources :header_characters
    resources :products
    resources :game_versions
    resources :posts do
      collection do
        post :preview
      end
    end
    resources :users do
      member do
        get :admin
        get :ban
      end
    end
    resources :comments do
      member do
        post :toggle
      end
    end
  end

  root "pages#index"

  get "/:id", to: "posts#show"
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id         :integer          not null, primary key
#  image      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Product < ActiveRecord::Base
  translates :title, :kind, :producer, :summary,
             fallbacks_for_empty_translations: true

  mount_uploader :image, ProductImageUploader

  validates :title, presence: true
end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < AdminController
    expose :product, attributes: :product_params
    expose_decorated(:products) {
      Product.all.includes :translations
    }

    def show
      self.product = product.decorate
    end

    def create
      if product.save
        redirect_to action: :show, id: product.id
      else
        flash[:danger] = "Algo salió mal"
        render :new
      end
    end
    alias_method :update, :create

    def destroy
      product.destroy
      redirect_to action: :index
    end

    private

    def product_params
      params.require(:product).permit :title, :image, :image_cache, :kind, :producer, :summary
    end

    def set_active
      @active_item = :productos
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include Commentable

  expose :page
  expose_decorated(:products) {
    Product.all.with_translations I18n.locale
  }

  alias_method :commentable, :page

  def index
    self.page = Page.otros_productos
  end
end

app/views/admin/products/_form.html.slim
h1 = "#{product.new_record? ? "Nuevo" : "Editar"} producto"

= render "shared/locale"

= simple_form_for [:admin, product] do |f|
  .form-group = f.input :title, input_html: { class: "form-control" }
  .form-group
    = f.hidden_field :image_cache
    = f.input :image, as: :file, input_html: { class: "form-control" }
    - if f.object.image?
      = image_tag f.object.image, class: "product-image-small"
  .form-group = f.input :kind, input_html: { class: "form-control" }
  .form-group = f.input :producer, input_html: { class: "form-control" }
  .form-group
    = f.input :summary, input_html: { class: "form-control"}
    = gfm_and_html_support
  .actions
    - unless product.new_record?
      = link_to "Eliminar", admin_product_path(product), class: "btn btn-link", method: :delete, data: { confirm: "¿Estás seguro? Esta acción es irreversible" }
    = link_to "Cancelar", (product.new_record? ? admin_products_path : admin_product_path(product)), class: "btn btn-link"
    = f.submit "Enviar", class: "btn btn-primary", data: { disable_with: "Enviando" }

app/views/admin/products/_product.html.slim
= link_to admin_product_path(product), class: "model_on_list" do
  = product.tiny_image
  h3 = product.title

app/views/admin/products/edit.html.slim
= render "form"

app/views/admin/products/index.html.slim
h1 Productos

= render "shared/locale"

.pull-right
  = link_to "", new_admin_product_path, class: "btn btn-default glyphicon glyphicon-plus"

- if products.any?
  = render products
- else
  h3 No hay productos

app/views/admin/products/new.html.slim
= render "form"

app/views/admin/products/show.html.slim
= render "shared/locale"

.product
  h1 = product.title
  .pull-right
    = link_to "", edit_admin_product_path(product), class: "btn btn-default glyphicon glyphicon-edit"
  = product.image
  .field
    span.label Producto:
    = product.kind
  .field
    span.label Productor:
    = product.producer
  .field
    span.label Resumen:
    = product.summary