config/routes.rb
require "admin_constraint"

SamsaWebsite::Application.routes.draw do
  match "/auth/:provider/callback", to: "sessions#create", via: [:get, :post]

  get "login", to: "sessions#index", as: :login
  get "logout", to: "sessions#destroy", as: :logout
  post "game_download", to: "game_download#create"

  resources :products, only: :index
  resources :news, only: :index

  concern :commentable do
    member do
      get :random_comment
    end
    resources :comments, only: :create do
      member do
        post "vote/:value", to: "comments#vote", as: :vote
      end
    end
  end

  resources :pages, only: :show do
    concerns :commentable
  end
  resources :posts, path: :news, only: :show do
    concerns :commentable
  end

  get :admin, to: "admin#index", constraints: AdminConstraint.new
  namespace :admin do
    resources :pages, only: [:index, :show]
    resources :preferences
    resources :media
    resources :header_characters
    resources :products
    resources :game_versions
    resources :posts do
      collection do
        post :preview
      end
    end
    resources :users do
      member do
        get :admin
        get :ban
      end
    end
    resources :comments do
      member do
        post :toggle
      end
    end
  end

  root "pages#index"

  get "/:id", to: "posts#show"
end

app/models/header_character.rb
# == Schema Information
#
# Table name: header_characters
#
#  id                  :integer          not null, primary key
#  nombre              :string(255)      not null
#  profundidad         :integer          default(1)
#  posicion_horizontal :integer          default(0)
#  posicion_vertical   :integer          default(0)
#  created_at          :datetime
#  updated_at          :datetime
#

class HeaderCharacter < ActiveRecord::Base
# validations
  validates :nombre, presence: true, uniqueness: true

end

app/controllers/admin/header_characters_controller.rb
module Admin
  class HeaderCharactersController < PreferencesController
    expose :header_character, attributes: :header_character_params

    def show
      self.header_character = header_character.decorate
    end

    def create
      if header_character.save
        redirect_to admin_preferences_path, success: "Creado"
      else
        render :new
      end
    end

    def update
      if header_character.update(header_character_params)
        redirect_to admin_preferences_path, success: "Actualizado"
      else
        render :edit
      end
    end

    def destroy
      header_character.destroy
      redirect_to action: :index
    end

    private

    def header_character_params
      params.require(:header_character).permit :nombre, :profundidad, :posicion_horizontal, :posicion_vertical
    end
  end
end

app/views/admin/header_characters/_form.html.slim
h1 = "#{header_character.new_record? ? "Nuevo" : "Editar"} personaje"

= simple_form_for [:admin, header_character] do |f|
  .form-group
    = f.input :nombre, input_html: { class: "form-control" }
    .help-block
      | Las imágenes se buscan en:
      ul
        li
          code
            | /images/header_characters/header_[nombre].png
        li
          code
            | /images/header_characters/header_[nombre]@2x.png
  .form-group = f.input :profundidad, input_html: { class: "form-control" }
  .form-group
    = f.input :posicion_horizontal, label: "Margen Horizontal", as: :range, input_html: { max: 100 }
    .pull-left Izquierda
    .pull-right Derecha
    .clearfix
  .form-group
    = f.input :posicion_vertical, label: "Margen Vertical", as: :range, input_html: { min: -150, max: 150}
    #posicion_vertical_value.align_center
  .header-preview
    = render "other_characters"
    = header_character.decorate.avatar classes: "current-character"
  .post-header-preview
  .actions
    = link_to "Eliminar", admin_header_character_path(header_character), class: "btn btn-danger", method: :delete, data: { confirm: "¿Estás seguro?" }
    = f.submit "Enviar", class: "btn btn-default", data: { disable_with: "Enviando" }

= javascript_tag "new Atixx.HeaderCharactersPositionHelper();"

app/views/admin/header_characters/_header_character.html.slim
= link_to admin_header_character_path(header_character), class: "col-xs-4 header_character_on_list model_on_list" do
  = header_character.avatar
  .clearfix
  h4 = header_character.nombre

app/views/admin/header_characters/_other_characters.html.slim
- all_header_characters.each do |character|
  = character.decorate.avatar(classes: "secondary-character") unless character == header_character

app/views/admin/header_characters/edit.html.slim
= render "form"

app/views/admin/header_characters/new.html.slim
= render "form"

app/views/admin/header_characters/show.html.slim
h2 = header_character.nombre
= header_character.avatar

.actions = link_to "Editar", edit_admin_header_character_path, class: "btn btn-default"